version: "3"

services:
  
  # The Database
  database:
    image: mysql:5.7.28
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=AHtCmBQ4S6zyZfUf"
      - "MYSQL_DATABASE=parking_db"
      - "MYSQL_USER=root"
    ports:
      - "33061:3306"

  # The Application 
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - "8000:5000"
    depends_on:
      - database
    restart: on-failure

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - "ADMINER_DESIGN='pepa-linha-dark'"
volumes:
  dbdata: